import {Metadata} from "next"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//children is {children} : {children: React.ReactNode}
export default function RootLayout({ children } : {children: React.ReactNode}) {//layout.js is around my page.js so any jsx or any logic goes are at my children proped and rendered  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}  {/*my children goes at my body cause my children parameter is what makes my content activate*/}
      </body>
    </html>
  );
}
